version: '3'
services:
  familyapp:
    container_name: familyapp
    build: ./FamilyApp
    ports:
      - "8081:8081"
    depends_on:
      - database
  familymemberapp:
    container_name: familymemberapp
    build: ./FamilyMemberApp
    ports:
      - "8082:8082"
    depends_on:
      - familyapp
  database:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "3307:3306"
    restart: always